spring:
  profiles: 
    active: test

    
 
---
server:
  port: 8201
  
spring:
  profiles: dev
test:
  config: ceshi-dev-06
    
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: test-cloud-test-2.0
test:
  config: ceshi-test    
